#pragma once
#include "CoreMinimal.h"
#include "EBGUAttrFloat.generated.h"

UENUM(BlueprintType)
enum class EBGUAttrFloat : uint8 {
    None,
    HpMax,
    MpMax,
    B1StunMax = 6,
    StaminaDepletedLimit,
    StaminaMax,
    SkillSuperArmorMax = 10,
    TransEnergyMax,
    EnergyMinConsume,
    EnergyConsumeSpeed,
    EnergyIncreaseSpeed,
    SpecialEnergyMax,
    FabaoEnergyMax,
    VigorEnergyMax,
    BlockCollapseArmorMax = 21,
    FreezeAbnormalAccMax = 23,
    BurnAbnormalAccMax,
    PoisonAbnormalAccMax,
    ThunderAbnormalAccMax,
    BlindSlotMax,
    BloodBottomNumMax = 36,
    PelevelMax,
    ShieldMax,
    PevalueMax,
    YinAbnormalAccMax,
    YangAbnormalAccMax,
    HpMaxMul = 51,
    MpMaxMul,
    AtkMul,
    DefMul,
    B1StunMaxMul = 56,
    StaminaDepletedLimitMul,
    StaminaMaxMul,
    StaminaRecoverMul,
    KptturnSpeedMul = 65,
    FreezeAbnormalAccMaxMul = 73,
    BurnAbnormalAccMaxMul,
    PoisonAbnormalAccMaxMul,
    ThunderAbnormalAccMaxMul,
    YinAbnormalAccMaxMul,
    YangAbnormalAccMaxMul,
    StaminaCostMultiperMul,
    TransEnergyMaxMul = 81,
    EnergyMinConsumeMul,
    EnergyConsumeSpeedMul,
    EnergyIncreaseSpeedMul,
    HpMaxBase = 101,
    MpMaxBase,
    AtkBase,
    DefBase,
    B1StunMaxBase = 106,
    StaminaDepletedLimitBase,
    StaminaMaxBase,
    StaminaRecoverBase,
    SkillSuperArmorMaxBase,
    CritRateBase,
    CritMultiplierBase,
    TenacityBase = 114,
    KptturnSpeedBase,
    EarPlugBase,
    CritRateDefBase,
    CritDmgMulDefBase,
    DmgAdditionBase,
    DmgDefBase,
    BlockCollapseArmorMaxBase,
    DingshenDefAdditionBase,
    FreezeAbnormalAccMaxBase,
    BurnAbnormalAccMaxBase,
    PoisonAbnormalAccMaxBase,
    ThunderAbnormalAccMaxBase,
    FreezeAtkBase = 128,
    BurnAtkBase,
    PoisonAtkBase,
    ThunderAtkBase,
    FreezeDefBase,
    BurnDefBase,
    PoisonDefBase,
    ThunderDefBase,
    BloodBottomNumMaxBase,
    PelevelMaxBase,
    ShieldMaxBase,
    PevalueMaxBase,
    YinAbnormalAccMaxBase,
    YangAbnormalAccMaxBase,
    YinAtkBase,
    YangAtkBase,
    YinDefBase,
    YangDefBase,
    StaminaCostMultiperBase,
    TransEnergyMaxBase,
    EnergyMinConsumeBase,
    EnergyConsumeSpeedBase,
    EnergyIncreaseSpeedBase,
    Hp,
    Mp,
    Atk,
    Def,
    B1Stun = 156,
    Stamina = 158,
    StaminaRecover,
    SkillSuperArmor,
    CritRate,
    CritMultiplier,
    Tenacity = 164,
    KptturnSpeed,
    EarPlug,
    CritRateDef,
    CritDmgMulDef,
    DmgAddition,
    DmgDef,
    BlockCollapseArmor,
    DingshenDefAddition,
    FreezeAbnormalAcc,
    BurnAbnormalAcc,
    PoisonAbnormalAcc,
    ThunderAbnormalAcc,
    BlindSlot,
    FreezeAtk,
    BurnAtk,
    PoisonAtk,
    ThunderAtk,
    FreezeDef,
    BurnDef,
    PoisonDef,
    ThunderDef,
    BloodBottomNum,
    Pelevel,
    CurEnergy,
    SpecialEnergy,
    Shield,
    Pevalue,
    YinAbnormalAcc,
    YangAbnormalAcc,
    YinAtk,
    YangAtk,
    YinDef,
    YangDef,
    ExpDropAddition,
    SpiritDropAddition,
    StaminaCostMultiper,
    FabaoEnergy,
    VigorEnergy,
    CommDropAddition,
    AttrFloatMax,
    EnumMax = 254,
};

