#pragma once
#include "CoreMinimal.h"
#include "EBGUFSMEventName.generated.h"

UENUM(BlueprintType)
enum class EBGUFSMEventName : uint8 {
    FSM_EVENT_LIFE_HASTARGET,
    FSM_EVENT_LIFE_GOHOME = 10,
    FSM_EVENT_LIFE_ARRIVEHOME,
    FSM_EVENT_LIFE_GAZEANDSURROUND,
    FSM_EVENT_LIFE_DIE = 1,
    FSM_EVENT_LIFE_REVIVE,
    FSM_EVENT_LIFE_STANDBY,
    FSM_EVENT_NONCOMBAT_WARNNING,
    FSM_EVENT_NONCOMBAT_IDLE,
    FSM_EVENT_BATTLE_BEHIT,
    FSM_EVENT_BATTLE_ATTACK,
    FSM_EVENT_BATTLE_WANDER,
    FSM_EVENT_BATTLE_STALEMATE,
};

