#pragma once
#include "CoreMinimal.h"
#include "EBGUFSMStateName.generated.h"

UENUM(BlueprintType)
enum class EBGUFSMStateName : uint8 {
    FSM_STATE_LIFE,
    FSM_STATE_LIFE_RETURNHOME = 9,
    FSM_STATE_LIFE_DEAD = 1,
    FSM_STATE_BATTLE,
    FSM_STATE_BATTLE_ATTACK,
    FSM_STATE_BATTLE_WANDER,
    FSM_STATE_BATTLE_STALEMATE,
    FSM_STATE_NONCOMBAT,
    FSM_STATE_NONCOMBAT_WARNNING,
    FSM_STATE_NONCOMBAT_IDLE,
    FSM_STATE_REVOLVEAROUND = 11,
    FSM_STATE_NEUTRALANIMAL_PATROL,
    FSM_STATE_NEUTRALANIMAL_BATTLE,
    FSM_STATE_NEUTRALANIMAL_ESCAPE,
    FSM_STATE_INVALID = 20,
};

