#pragma once
#include "CoreMinimal.h"
#include "CGI_Loading.generated.h"

UENUM(BlueprintType)
enum class CGI_Loading : uint8 {
    HasArchive,
    IsInStartUpLevel,
    IsInBattleLevel,
    IsInDefaultBattleLevel,
    HasArchiveIdInContext,
    IsInServer,
    IsInDedicateServer,
    IsInListenServer,
    IsStandAlone,
    IsInNetClient,
    IsInPIEClient,
    TravelUrlIsListen,
    TravelUrlHasHost,
    IsEnableLoadingUserInput,
    HasPlayerLoginBtlSvr,
    IsInToilet,
    IsInContextLevel,
    TeleportNeedLevelTravel,
    SwitchTeleportType,
    IsReplayWorldLoadFinish,
    PlayerGameStateCheck,
    IsInPreviewSeqContext,
    NeedSwitchPlayerGameMode,
    MonsterTeleportArchiveExist,
    BattleLevelTravelNeedWaitCameraBlend,
    IsInMap,
    OpenSeamlessLevelTravel,
    IsNeedPostLeaveLevel,
    IsNeedPreEnterLevel,
    IsNeedResetGameInstanceData,
    CheckGlobalTravelMode,
    IsNeedOpenLoadingScreen,
    IsNeedCloseLoadingScreen,
    IsFirstStartGame,
    CheckGMFlagsSupportUnknownTravel,
    IsDriverVersionMismatch,
    IsPlayGoDownloadIncomplete,
    SwitchFillContextArchiveDataType,
    IsNeedPreStartGameProcess,
    SwitchSaveArchiveDegree,
    DetermineTravelLevelByHandlingArchive,
};

