#pragma once
#include "CoreMinimal.h"
#include "InputTipsType.generated.h"

UENUM(BlueprintType)
enum class InputTipsType : uint8 {
    Min,
    Obs_Mode = 10,
    TalentMain_Select = 20,
    TalentMain_ResetSelect,
    Talent_Reset,
    SpellConfig_Select = 30,
    SpellConfig_SelectNotSet,
    Equip_EquipSlot = 40,
    Equip_QuickItemSlot_HadConfig,
    Equip_QuickItemSlot_NotConfig,
    Equip_AccessorySlot_HadConfig,
    Equip_AccessorySlot_NotConfig,
    Equip_Accessory_HadConfig,
    Equip_Accessory_NotConfig,
    Equip_Accessory_CurConfig,
    Equip_Min_CanEnterTPMode,
    Equip_EquipSlot_CanEnterTPMode,
    Equip_QuickItemSlot_HadConfig_CanEnterTPMode,
    Equip_QuickItemSlot_NotConfig_CanEnterTPMode,
    Equip_AccessorySlot_HadConfig_CanEnterTPMode,
    Equip_AccessorySlot_NotConfig_CanEnterTPMode,
    Bag_CanUse = 60,
    Bag_CantUse,
    Bag_HadConfig,
    Bag_SlotNotConfig,
    Bag_SlotHadConfig,
    Bag_ItemConfiging_NotConfig,
    Bag_ItemConfiging_HadConfig,
    Bag_ItemConfiging_CurConfig,
    Shop_CanBuy = 80,
    Shop_CantBuy,
    Shop_Sell,
    Shop_SecConfirm,
    WeaponBuild_CanShowTree = 90,
    WeaponBuild_CantShowTree,
    WeaponBuild_ShowTree,
    Soaking_MainPage_Wine = 100,
    Soaking_WineList_NotConfig,
    Soaking_WineList_CurConfig,
    Soaking_MainPage_WineItemSlot_NotConfig,
    Soaking_MainPage_WineItemSlot_HadConfig,
    Soaking_WineItemList_HadConfig,
    Soaking_WineItemList_NotConfig,
    Soaking_WineItemList_CurConfig,
    Medicine_Interact = 120,
    Medicine_Shrine,
    Medicine_Interact_Sort,
    Medicine_Shrine_Sort,
    Alchemy_Tips = 130,
    TravelNotes_Unfold = 140,
    TravelNotes_Fold,
    ChapterAward_CameraRoam = 150,
    ChapterAward_CameraRoam_Start,
    ChapterAward_CameraRoam_Middle,
    ChapterAward_CameraRoam_End,
    Learn_DSTalent_Menu_LeftFocusCanSwitch = 160,
    Learn_DSTalent_RebirthPoint_LeftFocusCanSwitch,
    Learn_DSTalent_Menu_LeftFocusCantSwitch,
    Learn_DSTalent_RebirthPoint_LeftFocusCantSwitch,
    Learn_DSTalent_Menu_RightFocus,
    Learn_DSTalent_RebirthPoint_RightFocus,
    Farm_Can_Collect = 180,
    Farm_Cant_Collect,
    Farm_LongPress_Button,
    Farm_Output_Info,
    Farm_Seed_Info,
    SoulSkill_Item = 190,
    SoulSkill_LongPress,
    BenchMark_Report = 200,
    Archive_LoadArchive = 210,
    Setting_BenchMark = 220,
    Setting_Main,
    Setting_Exit,
    Setting_Normal_Confirm,
    Setting_Normal,
    Setting_BenchMark_Quality_Confirm,
    Setting_BenchMark_Quality,
    Setting_BenchMark_Confirm,
    Setting_Quality_Confirm,
    Setting_Quality,
    Setting_NoConfirm,
    Setting_Confirm,
    EditionAward_Item = 240,
    EditionAward_LongPress,
    MeditationPoint_CanPlay = 250,
    MeditationPoint_CantPlay,
    MeditationPoint_Playing,
};

