#pragma once
#include "CoreMinimal.h"
#include "BuffAndSkillEffectType.generated.h"

UENUM(BlueprintType)
enum class BuffAndSkillEffectType : uint8 {
    None,
    SkillDamage,
    AddAttr,
    RecoverAttr,
    AddBuffByBone,
    RemoveBuff,
    TriggerProjectileReaction,
    SetSimpleState,
    RemoveSimpleState,
    Sucide,
    SwitchLocomotionAnimGroup,
    DragFarCamera,
    DestroyFireProjectile = 13,
    Teleport = 15,
    ResetSkillCd = 17,
    AttackStiff,
    AwakePartner,
    SpawnProjectile,
    SwitchBullet,
    SwitchEnvironment,
    TriggerScreenEffect,
    EnableCollisionChanel,
    TriggerHidden,
    PauseAi,
    CleanBulletCtrable,
    SummonUnit,
    SwitchMmgroup,
    DestroyBullet,
    BulletSwitchSelf,
    SwitchBehaviorTree,
    HideOrShowMesh,
    SwitchAttackerAbnormalDispId,
    HiddenBloodBar = 36,
    ChangeMoveSpeed = 38,
    DrawLineToTarget,
    BulletsSimpleSpawn,
    BulletAutoAttack,
    BulletScopeMonitor,
    SpawnEmitter,
    DestroyAllSummons = 45,
    AddBuff,
    SetMatsParamAdvanced,
    SetMatsLayerParamAdvanced,
    SwitchPlayerCamInfoId = 51,
    SpawnGhostActor,
    ModifyCollisionHitWeight,
    SwitchCollisionHitMove = 56,
    TriggerChargeNextStage,
    AddBuffByBuffGroupTotalLayers = 63,
    TimeScale,
    ModifyManagedEffect,
    BulletHitBack,
    MoveToPoint,
    TriggerPassiveSkill,
    TriggerTttbFeedback,
    CallSummonUseSkill,
    ScalingBulletSpd,
    SpawnFxbyDispConfigWithEmitterInfo,
    DropAttrItem,
    SwitchTeamId = 75,
    EscapeAfterDeath,
    SwitchStateLib,
    InitiatePriorityAction,
    BeginModularSimulation,
    DetachModularParts,
    RestoreModularParts,
    ModularBreakDown,
    PlayCameraShake,
    SetStaminaRecoverMul = 85,
    DestroyProjectileById,
    CostAttr,
    SetPartRuleId,
    SetPartActive,
    ResetBlockInfo = 91,
    ActivateWeapons,
    DeactivateWeapons,
    SwitchCollisionProfile,
    AccumulateAbnormalValue,
    RemoveAbnormalFinalEffectByStep,
    ClearAbnormalState,
    SwitchSkillCameraGroup = 99,
    SummonRecall,
    RecoveryPartDamageValue,
    FrozenFracture = 103,
    DoFreshMultiTarget,
    InterruptRestoreModularParts,
    HitDestructibleActor,
    EnableAssistCollision,
    RemoveBuffByCategory,
    TauntTarget,
    DestroyModularParts,
    KjlrandomLightning,
    EnablePreciseDodge,
    DecreaseAbnormalAccValue,
    ModifyCooldown,
    DisableCapsuleCollision,
    DisableMeshCollision,
    DisableGravity,
    CostPlayerTransEnergy,
    SetPhantomRushConfig,
    DestroySummonsById,
    SetUnitBattleBgm,
    SetBgmState,
    ForceLockTarget,
    ApplyMasterAttrByRate,
    AddAllSummonLifeTime,
    ImmuneHardMove,
    SuperArmorLevelModify,
    FilterBuff,
    FilterSkillEffect,
    SetLockPartHp,
    BulletSwitchSelfNoImmediately,
    DisableInteract,
    NeverIntoBattle,
    IncreasePevalue,
    ClearPevalue,
    SwitchPeconfig,
    SetBgmSwitchPaused,
    AssistBreakFrozen,
    SwitchCameraGroup,
    SwitchTransMusic,
    CastProjectileLifeOver,
    DisableCameraLockPoint,
    DisableAutoLockPoint,
    AddPhysicsImpulse,
    ThrowUpDeadUnit,
    SetMpcParamByFloatCurve,
    ApplyIllusionEquipOverride,
    AddPostProcessMaterial,
    FixHpByRate,
    SwitchBulletAndSmartSelectTarget,
    InheritedHpByRate,
    SetPreciseCompRelativeScale,
    SwitchFreeCameraMode,
    RelieveImmobilized,
    EnterSpiderSilkEntangle,
    SetGmcustomTimeDilation,
    PlayerTrans,
    MagicallyChange,
    MagicallyChangeRecover,
    BreakCloudMove,
    DecreaseLifeSavingHairCoolDown,
    ActiveExtLifeSavingHair,
    ApplyEnvironmentMask,
    ToggleWeaponStatus,
    SetHitMoveUnmovable,
    SetEnableVigourDropManually,
    MultiTargetBulletSwitchToBackNestProjectile,
    ResetSealingSpell,
    EnumMax,
};

