#pragma once
#include "CoreMinimal.h"
#include "ModifyMethod.generated.h"

UENUM(BlueprintType)
enum class ModifyMethod : uint8 {
    SkillCooldown,
    SkillEffectFloatN,
    SkillEffectIntN,
    BuffDuration,
    BuffEffectFloatN,
    BuffEffectIntN,
    BuffActiveConditionParams,
    SkillEffectActiveConditionParams,
    ChargeSkillMoveSpeed,
    ChargeSkillMaxChargeTime,
    SkillEffectTargetCount,
    SkillEffectRange,
    BuffInterval,
    BuffMaxLayer,
    SkillMinAttrCostBase1,
    SkillMinAttrCostBase2,
    BuffTargetCount,
    BuffRange,
    SkillIsComboSkill,
    RollSkillEnabled,
    ChargeSkillLevelConfigIndex,
    PlayerSkillCtrlAttackRange,
    ImmobilizeDuration = 30,
    ImmobilizeTargetCount,
    ImmobilizeRange,
    ImmobilizeEffect,
    IronBodyBeginWindowTime,
    IronBodyWindowTimeLength,
    IronBodyBuff,
    SummonCommAliveTime,
    SummonCommBuffListN,
    PlayerCommDodgeStartSkillId,
    PlayerCommPreciseDodgeStartSkillId,
    SkillEffectDamageExpandN,
    PotentialEnergyConfigIndex,
    PartRuleReduceParamsN,
    ProjectileLifeTime,
    BuffDelayTime,
    AttrCopyFactor,
    LifeSavingHairDefaultCd,
    LifeSavingHairEffectN,
    LifeSavingHairBuffN,
    SupreArmorValue,
    StaminaCostMoveFast,
    StaminaDepletedLimitBase,
    PhantomRushDuration,
    PhantomRushSkillId,
    PhantomRushBeginAddBuffIdlist,
    PotentialEnergyProtectTime,
    PotentialEnergyDecreaseValue,
    PotentialEnergyLevelValue,
    EffectiveHitProjectileEffectPevalueSwitchRatio,
    EffectiveHitProjectileEffectCostAttrType,
    EffectiveHitProjectileEffectAttrSwitchRatio,
    PlayerCommFallingDamageMultiplier,
    SkillMinAttrCostRatio1,
    SkillMinAttrCostRatio2,
    SealingSpellSkillDuration,
};

