#pragma once
#include "CoreMinimal.h"
#include "EBGUSimpleState.generated.h"

UENUM(BlueprintType)
enum class EBGUSimpleState : uint8 {
    Normal,
    ImmueDamage,
    CantAttack,
    CantMove,
    CancelLifeSavingCD,
    IgnoreTargetElemDef,
    IgnoreAllInput,
    CanHitBullet,
    PEClearProtect,
    Immobilizing,
    ImmueDmgExceptElementDmg,
    ImmueFreezeAcc,
    BanInputButCamera,
    CanBlendToDeadAM,
    ImmueFrozenBrokenAM,
    CantBeDead,
    CantPlayShakeFreezeAM,
    ImmueStiff,
    ImmueImmobilizing,
    ImmueAnimationSyncing,
    ForbidLifeSavingHair,
    BreakPart2Weak = 22,
    ImmueBurnAcc,
    ImmuePoisonAcc,
    ImmueThunderAcc,
    CantSweepUnit,
    UseCarMontageMoveMode,
    CantBeSweepChecked,
    ImmueDeadZone,
    CantBeLock,
    StaminaDepleted,
    SeduceAttack,
    CancelSkillCD,
    MoveSlowly = 35,
    CantBeBaseTarget = 38,
    SkillSuperArmor,
    StaminaLock,
    HRCounterattackProtectOneFrame = 42,
    BreakSkillSuperArmor,
    Silent,
    BounceAttack,
    CanForceAttackInChargeSkill = 47,
    CanTriggerBeHitAdditiveAnim,
    DynamicUpperBodyMode = 50,
    DynamicLeftArmMode,
    DynamicRightArmMode,
    LockStateWalking,
    FlyControlMode,
    TPSMode,
    PlayerInSeq,
    ImmueAttackPerformEffect,
    DisableFreezeFrame,
    ImmueBeAttackedPerformEffect,
    KeepMMRunning = 61,
    CanDefeatTTTB,
    Mute,
    LockRotation,
    Imperceptible = 66,
    IgnoreHostile = 68,
    InPhaseTransition,
    InPointAttraction = 71,
    ForcePerformance,
    PlayerCantLock,
    CanTriggerBlockNormal,
    ForceSkill,
    BreakBlock,
    InAnimationSyncing,
    CanTriggerBlockInSPState,
    BreakBlock2Weak,
    InTTTB,
    MontageSectionJumpApproved,
    Frozen,
    FreezeImmue,
    BurnImmue,
    PoisonImmue,
    ThunderImmue,
    PhysicsSimulationMoveMode,
    PhantomRush,
    BreakImmobilize2Weak,
    BeTaunted,
    SplineFlyWaiting,
    PlayerDeadNoPunish,
    SpiderSilkyHardMoving,
    FrozenMoving,
    MuddyMoving,
    WinddyMoving,
    ImmuneNeutral,
    ImmunePositive,
    ImmuneNegative,
    InUpdraft,
    Interacting,
    CantShowBlood,
    PendingDeathInAnimationSyncing,
    IgnoreSpell,
    IgnoreRollSkill,
    IgnoreUnitTransSkill = 107,
    IgnoreSpinLightInput,
    IgnoreInteractInput,
    IgnoreMoveInput,
    IgnoreJumpInput,
    IgnoreLightAttackInput,
    IgnoreHeavyAttackInput,
    YinImmue,
    YangImmue,
    CommonDamageImmue,
    StrongDamageImmue,
    IgnoreAlignCapsule2Surface,
    WithinOceanSea,
    NoAutoTransformBack,
    DeadUseFixCamera,
    IgnoreMoveBackInput = 123,
    IgnoreXAxisMoveInput,
    DisableAutoRecoverFreeze,
    DisableAutoRecoverBurn,
    DisableAutoRecoverPoison,
    DisableAutoRecoverThunder,
    DisableAutoRecoverYin,
    DisableAutoRecoverYang,
    CantHatredTick = 133,
    Berserk,
    IgnoreBattleInfoInUnitBar,
    CantTransBack,
    TransEnergyLock,
    PELock,
    DamageTransfer,
    RidingExitingStatus,
    CantTrans,
    BanLegacyTalent,
    CloudMove,
    CricketIdle,
    DisableImmobilizedBreakAnim,
    EnableSpecialImmobilizedBreakAnim,
    FabaoEnergyLock,
    VigorEnergyLock,
    CantGainFabaoEnergy,
    CantGainVigorEnergy,
    InteractCricketLoop,
    InInteractAnimationSyncing,
    RefuseAttackRotation,
    RefuseAMScale,
    DisableHRCounterAttack,
    DisableDamageNumUI,
    Camouflage,
    CantShowLock,
    PreAnimationSyncing,
    IgnoreVigorSkill,
    CantInVigorSkill,
    CantInteract,
    Sentry,
    LockMP,
    CantBeAutoLockTarget,
    CantShowDamageUI,
    TargetCantShowLock,
    CantTriggerPreciseDodge,
    BanTrans2DaSheng,
    CantCastFaBao,
    CantTransInSeq,
    EnumMax,
};

